FROM debian:bookworm-slim
RUN apt-get update \
&& apt-get install iproute2 iputils-ping net-tools -y 
#RUN ip route
#RUN ip route add 192.168.21.1 via 192.168.21.1
# 
#RUN ip route add default via 192.168.21.3